react-component/color-picker

README.md, src/ColorPicker.jsx, src/Panel.jsx, src/Params.jsx
close #9
加一个参数，可以禁止store的调用，不然服务端无法用。
=> feat: add prop to disable store require

src/ColorPicker.jsx
Hi, I found setState({alpha: 0}) not working, so I fixed it.
=> bugfix while alpha is 0

src/Board.jsx
=> Support touch events in Board

README.md
=> Add Edge to supported browsers.

.travis.yml, examples/custom-trigger.js, examples/panel.js, package.json, src/Alpha.jsx, src/Board.jsx, src/ColorPicker.jsx, src/Panel.jsx, src/Params.jsx, src/Preview.jsx, src/Ribbon.jsx, src/utils/validationColor.js
https://github.com/react-component/color-picker/issues/35
https://github.com/react-component/color-picker/pull/36
=> Stevenxxiu master #35

README.md, examples/simple.js, src/ColorPicker.jsx, src/Panel.jsx
You would be able to add a className to ColorPicker or Panel to make custom changes to de default CSS
=> Ability to add other classnames to picker

package.json, src/Alpha.jsx, src/Board.jsx, src/ColorPicker.jsx, src/Panel.jsx, src/Params.jsx, src/Preview.jsx, src/Ribbon.jsx
Update to be compatible with React 16.x and ^15.5.
---
Close: #41
=> Resolves issue #41

README.md, assets/index/Layout.less, assets/index/Panel.less, assets/index/Params.less, examples/panel.js, package.json, src/ColorPicker.jsx, src/Panel.jsx, src/Params.jsx
=> ability to hide alpha

History.md, assets/index/Params.less, assets/index/Preview.less, examples/panel.js, examples/simple.js, package.json, src/Alpha.jsx, src/Board.jsx, src/ColorPicker.jsx, src/Panel.jsx, src/Params.jsx, src/Preview.jsx, src/Ribbon.jsx, src/helpers/color.js, src/helpers/percentage.js
=> use tinycolor2 instead  colr

package.json, src/ColorPicker.jsx, src/Panel.jsx
may not be elegant enough but fixes https://github.com/react-component/color-picker/issues/48
=> add react 16 compatility

assets/index/Board.less, src/Board.jsx, src/Params.jsx, src/helpers/color.js
Trying to avoid of using constant WIDTH and HEIGHT dimesions of Board.
And replace absolute(in pixels) values top and left of marker with relative in percents.
=> Don't use hardcoded dimensions for Board.

src/ColorPicker.jsx
Fixed #56 
只有用户操作时才会触发 onChange，其他 case 不触发 onChange
=> fix: do not trigger onChange when toggle panel

.husky/pre-commit, assets/index.less, docs/example/basic.tsx, docs/index.md, jest.config.js, package.json, src/ColorPicker.tsx, src/Panel.tsx, src/TriggerPanel.tsx, src/components/DataBar.tsx, src/components/Gradient.tsx, src/components/Picker.tsx, src/components/Point.tsx, src/components/Slider.tsx, src/components/Transform.tsx, src/context.ts, src/hooks/useColorDrag.ts, src/index.tsx, src/interface.ts, src/shape/Square.tsx, src/util.ts, tests/index.test.tsx, tsconfig.json
Generate new compnpnt `ColorPicker`.
Ref： [RFC: New Component: ColorPicker ](https://github.com/ant-design/ant-design/discussions/40974).
=> New Component: ColorPicker 

src/color.ts, src/util.ts
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |       fix color rgb transform problem    |
| 🇨🇳 Chinese |     修复rgb颜色的转换问题      |
⚠️ Please check all items below before requesting a reviewing. ⚠️
=> fix: rgb color transform

assets/index.less, src/ColorPicker.tsx, src/Panel.tsx, src/components/Picker.tsx, src/components/Slider.tsx, src/hooks/useColorDrag.ts, src/index.tsx, src/util.ts, tests/__snapshots__/index.test.tsx.snap, tests/index.test.tsx
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Fix `style` to `styles`    |
| 🇨🇳 Chinese |    修正 `style` 为 `styles`    |
⚠️ Please check all items below before requesting a reviewing. ⚠️
=> fix: rename style to styles

assets/index.less, src/ColorPicker.tsx, tests/__snapshots__/index.test.tsx.snap, tests/index.test.tsx
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Fix the popup window prefix to `prefix`    |
| 🇨🇳 Chinese |    修正弹窗前缀为 `prefix`    |
⚠️ Please check all items below before requesting a reviewing. ⚠️
=> fix: rename popup prefix to prefix

src/ColorPicker.tsx, src/Panel.tsx, src/components/Picker.tsx, src/components/Slider.tsx, src/hooks/useColorDrag.ts, src/interface.ts, tests/index.test.tsx
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix the misuse of dragging that causes pop-up windows to close   |
| 🇨🇳 Chinese |    修正拖动导致弹窗关闭的误操作    |
⚠️ Please check all items below before requesting a reviewing. ⚠️
=> fix: open misuse

package.json, src/ColorPicker.tsx, src/components/Handler.tsx, src/components/Picker.tsx, src/hooks/useColorDrag.ts
=> chore: improve type and add missing deps

README.md, assets/index.less, docs/demo/index.md, docs/example/basic.tsx, docs/example/disabled.tsx, docs/example/disabledAlpha.tsx, src/ColorPicker.tsx, src/components/Picker.tsx, src/components/Slider.tsx, src/hooks/useColorDrag.ts, src/interface.ts, tests/__snapshots__/index.test.tsx.snap, tests/index.test.tsx
implement  new API `disabled` `disabledAlpha` `onChangeComplete` ready for new feature.
=> feat: implement  new API `disabled` `disabledAlpha` `onChangeComplete`

docs/example/block.tsx, src/color.ts, src/util.ts
fix https://github.com/ant-design/ant-design/issues/42666
=> fix: not found convertHsb2Hsv

src/hooks/useColorDrag.ts
https://github.com/ant-design/ant-design/issues/43529
=> fix: should work after closing the browser menu

README.md, package.json
=> chore: fix style files not compile

package.json
fix https://github.com/react-component/color-picker/issues/237
=> chore: fix svg

src/color.ts, src/components/Picker.tsx, src/components/Slider.tsx, tests/index.test.tsx
由于 onDragChange 是在 onMouseMove 的时候被绑定到事件监听器上，所以存在闭包问题，取到的 color 永远是 mousedown 时的值。用 useEvent 包一层
=> fix: onDragChange closure issue

docs/demo/index.md, docs/example/basic.tsx, docs/example/components.tsx, src/ColorPicker.tsx, src/components/Slider.tsx, src/hooks/useColorDrag.ts, src/hooks/useComponent.ts, src/index.tsx, tests/__snapshots__/index.test.tsx.snap, tests/components.test.tsx
支持自定义 Slider，老的 Slider 作为 fallback（其实删了还能剩空间）。
=> feat: Support components
